export * from './app.service';
import { AppApi } from './app.service';
export * from './auth.service';
import { AuthApi } from './auth.service';
export * from './categories.service';
import { CategoriesApi } from './categories.service';
export * from './documents.service';
import { DocumentsApi } from './documents.service';
export * from './expense.service';
import { ExpenseApi } from './expense.service';
export * from './users.service';
import { UsersApi } from './users.service';
export const APIS = [AppApi, AuthApi, CategoriesApi, DocumentsApi, ExpenseApi, UsersApi];
