/**
 * Auth API (NestJS + Prisma)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateCategoryDto { 
    type: CreateCategoryDto.TypeEnum;
    name: string;
    /**
     * หมวดแม่ (ถ้าว่าง = หมวดระดับบนสุด)
     */
    parentId?: string;
    sortOrder?: number;
}
export namespace CreateCategoryDto {
    export const TypeEnum = {
        Income: 'income',
        Expense: 'expense'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


