/**
 * Auth API (NestJS + Prisma)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateExpenseDto { 
    /**
     * วันที่ (YYYY-MM-DD HH:mm:ss)
     */
    date?: string;
    type?: UpdateExpenseDto.TypeEnum;
    amount?: number;
    category?: string;
    note?: string;
}
export namespace UpdateExpenseDto {
    export const TypeEnum = {
        Income: 'income',
        Expense: 'expense'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


